spring:
   application:
      name: user-service
server:
   port: 8083
logging:
   application-insights:
      instrumentation-key: 2f53fcd9-b604-4e4e-947f-608701dbabd4      
   level:
      root: INFO
      org.epam: DEBUG   
# Specify the DNS URI of your Azure Cosmos DB, access key, DB id
azure:
   application-insights:
      instrumentation-key: 2f53fcd9-b604-4e4e-947f-608701dbabd4      
   cosmos:
      uri: https://smdata.documents.azure.com:443/
      key: hHeTPRstY0ySOm1guY7dTmQz8AKaokW4CMyOhqUN6F9Rpy8mRNLAznMcpg0KSot9KxZjHdqp2xA6z2QAD22kFw==
      database: smcosmodb
      populateQueryMetrics: true
